/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle?: string;
  siteDescription?: string;
  siteKeywords?: Array<string>;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  favicon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gradioEmbedUrl?: string;
  googleAnalyticsId?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  phone?: string;
  linkedinUrl?: string;
  githubUrl?: string;
  twitterUrl?: string;
  resumeFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    title?: string;
    _type: "file";
  };
  location?: string;
};

export type Technology = {
  _id: string;
  _type: "technology";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  category?: "frontend" | "backend" | "database" | "devops" | "ai-ml" | "mobile" | "tools";
  icon?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  iconIdentifier?: string;
  proficiencyLevel?: "beginner" | "intermediate" | "advanced" | "expert";
  description?: string;
  orderRank?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  longDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  technologies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "technology";
  }>;
  featured?: boolean;
  demoUrl?: string;
  githubUrl?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  orderRank?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Hero = {
  _id: string;
  _type: "hero";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: string;
  professionalPhoto?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  chatbotCta?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SiteSettings | SanityImageCrop | SanityImageHotspot | Contact | Technology | Project | Slug | Hero | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/queries/contact.ts
// Variable: CONTACT_QUERY
// Query: *[_type == "contact"][0] {    _id,    email,    phone,    linkedinUrl,    githubUrl,    twitterUrl,    resumeFile {      asset-> {        _id,        url,        originalFilename,        size      },      title    },    location  }
export type CONTACT_QUERYResult = {
  _id: string;
  email: string | null;
  phone: string | null;
  linkedinUrl: string | null;
  githubUrl: string | null;
  twitterUrl: string | null;
  resumeFile: {
    asset: {
      _id: string;
      url: string | null;
      originalFilename: string | null;
      size: number | null;
    } | null;
    title: string | null;
  } | null;
  location: string | null;
} | null;

// Source: ./sanity/queries/hero.ts
// Variable: HERO_QUERY
// Query: *[_type == "hero"][0] {    _id,    name,    tagline,    professionalPhoto {      asset-> {        _id,        url      },      alt,      hotspot,      crop    },    chatbotCta  }
export type HERO_QUERYResult = {
  _id: string;
  name: string | null;
  tagline: string | null;
  professionalPhoto: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  chatbotCta: string | null;
} | null;

// Source: ./sanity/queries/projects.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(orderRank asc, _createdAt desc) {    _id,    title,    slug,    description,    longDescription,    technologies[]-> {      _id,      name,      category,      iconIdentifier    },    featured,    demoUrl,    githubUrl,    images[] {      asset-> {        _id,        url      },      alt,      caption,      hotspot,      crop    },    orderRank  }
export type PROJECTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  longDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  technologies: Array<{
    _id: string;
    name: string | null;
    category: "ai-ml" | "backend" | "database" | "devops" | "frontend" | "mobile" | "tools" | null;
    iconIdentifier: string | null;
  }> | null;
  featured: boolean | null;
  demoUrl: string | null;
  githubUrl: string | null;
  images: Array<{
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
    caption: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  orderRank: number | null;
}>;
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && featured == true] | order(orderRank asc, _createdAt desc) {    _id,    title,    slug,    description,    technologies[]-> {      _id,      name,      category,      iconIdentifier    },    demoUrl,    githubUrl,    images[] {      asset-> {        _id,        url      },      alt,      caption,      hotspot,      crop    }  }
export type FEATURED_PROJECTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  technologies: Array<{
    _id: string;
    name: string | null;
    category: "ai-ml" | "backend" | "database" | "devops" | "frontend" | "mobile" | "tools" | null;
    iconIdentifier: string | null;
  }> | null;
  demoUrl: string | null;
  githubUrl: string | null;
  images: Array<{
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
    caption: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
}>;
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    slug,    description,    longDescription,    technologies[]-> {      _id,      name,      category,      icon {        asset-> {          _id,          url        },        alt      },      iconIdentifier,      proficiencyLevel    },    featured,    demoUrl,    githubUrl,    images[] {      asset-> {        _id,        url      },      alt,      caption,      hotspot,      crop    }  }
export type PROJECT_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  longDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  technologies: Array<{
    _id: string;
    name: string | null;
    category: "ai-ml" | "backend" | "database" | "devops" | "frontend" | "mobile" | "tools" | null;
    icon: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
      alt: string | null;
    } | null;
    iconIdentifier: string | null;
    proficiencyLevel: "advanced" | "beginner" | "expert" | "intermediate" | null;
  }> | null;
  featured: boolean | null;
  demoUrl: string | null;
  githubUrl: string | null;
  images: Array<{
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
    caption: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
} | null;

// Source: ./sanity/queries/siteSettings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    _id,    siteTitle,    siteDescription,    siteKeywords,    ogImage {      asset-> {        _id,        url      },      alt    },    favicon {      asset-> {        _id,        url      }    },    gradioEmbedUrl,    googleAnalyticsId  }
export type SITE_SETTINGS_QUERYResult = {
  _id: string;
  siteTitle: string | null;
  siteDescription: string | null;
  siteKeywords: Array<string> | null;
  ogImage: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  favicon: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  gradioEmbedUrl: string | null;
  googleAnalyticsId: string | null;
} | null;

// Source: ./sanity/queries/technologies.ts
// Variable: TECHNOLOGIES_QUERY
// Query: *[_type == "technology"] | order(category asc, orderRank asc, name asc) {    _id,    name,    category,    icon {      asset-> {        _id,        url      },      alt    },    iconIdentifier,    proficiencyLevel,    description,    orderRank  }
export type TECHNOLOGIES_QUERYResult = Array<{
  _id: string;
  name: string | null;
  category: "ai-ml" | "backend" | "database" | "devops" | "frontend" | "mobile" | "tools" | null;
  icon: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  iconIdentifier: string | null;
  proficiencyLevel: "advanced" | "beginner" | "expert" | "intermediate" | null;
  description: string | null;
  orderRank: number | null;
}>;
// Variable: TECHNOLOGIES_BY_CATEGORY_QUERY
// Query: *[_type == "technology" && category == $category] | order(orderRank asc, name asc) {    _id,    name,    category,    icon {      asset-> {        _id,        url      },      alt    },    iconIdentifier,    proficiencyLevel,    description  }
export type TECHNOLOGIES_BY_CATEGORY_QUERYResult = Array<{
  _id: string;
  name: string | null;
  category: "ai-ml" | "backend" | "database" | "devops" | "frontend" | "mobile" | "tools" | null;
  icon: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  iconIdentifier: string | null;
  proficiencyLevel: "advanced" | "beginner" | "expert" | "intermediate" | null;
  description: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"contact\"][0] {\n    _id,\n    email,\n    phone,\n    linkedinUrl,\n    githubUrl,\n    twitterUrl,\n    resumeFile {\n      asset-> {\n        _id,\n        url,\n        originalFilename,\n        size\n      },\n      title\n    },\n    location\n  }\n": CONTACT_QUERYResult;
    "\n  *[_type == \"hero\"][0] {\n    _id,\n    name,\n    tagline,\n    professionalPhoto {\n      asset-> {\n        _id,\n        url\n      },\n      alt,\n      hotspot,\n      crop\n    },\n    chatbotCta\n  }\n": HERO_QUERYResult;
    "\n  *[_type == \"project\"] | order(orderRank asc, _createdAt desc) {\n    _id,\n    title,\n    slug,\n    description,\n    longDescription,\n    technologies[]-> {\n      _id,\n      name,\n      category,\n      iconIdentifier\n    },\n    featured,\n    demoUrl,\n    githubUrl,\n    images[] {\n      asset-> {\n        _id,\n        url\n      },\n      alt,\n      caption,\n      hotspot,\n      crop\n    },\n    orderRank\n  }\n": PROJECTS_QUERYResult;
    "\n  *[_type == \"project\" && featured == true] | order(orderRank asc, _createdAt desc) {\n    _id,\n    title,\n    slug,\n    description,\n    technologies[]-> {\n      _id,\n      name,\n      category,\n      iconIdentifier\n    },\n    demoUrl,\n    githubUrl,\n    images[] {\n      asset-> {\n        _id,\n        url\n      },\n      alt,\n      caption,\n      hotspot,\n      crop\n    }\n  }\n": FEATURED_PROJECTS_QUERYResult;
    "\n  *[_type == \"project\" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    description,\n    longDescription,\n    technologies[]-> {\n      _id,\n      name,\n      category,\n      icon {\n        asset-> {\n          _id,\n          url\n        },\n        alt\n      },\n      iconIdentifier,\n      proficiencyLevel\n    },\n    featured,\n    demoUrl,\n    githubUrl,\n    images[] {\n      asset-> {\n        _id,\n        url\n      },\n      alt,\n      caption,\n      hotspot,\n      crop\n    }\n  }\n": PROJECT_BY_SLUG_QUERYResult;
    "\n  *[_type == \"siteSettings\"][0] {\n    _id,\n    siteTitle,\n    siteDescription,\n    siteKeywords,\n    ogImage {\n      asset-> {\n        _id,\n        url\n      },\n      alt\n    },\n    favicon {\n      asset-> {\n        _id,\n        url\n      }\n    },\n    gradioEmbedUrl,\n    googleAnalyticsId\n  }\n": SITE_SETTINGS_QUERYResult;
    "\n  *[_type == \"technology\"] | order(category asc, orderRank asc, name asc) {\n    _id,\n    name,\n    category,\n    icon {\n      asset-> {\n        _id,\n        url\n      },\n      alt\n    },\n    iconIdentifier,\n    proficiencyLevel,\n    description,\n    orderRank\n  }\n": TECHNOLOGIES_QUERYResult;
    "\n  *[_type == \"technology\" && category == $category] | order(orderRank asc, name asc) {\n    _id,\n    name,\n    category,\n    icon {\n      asset-> {\n        _id,\n        url\n      },\n      alt\n    },\n    iconIdentifier,\n    proficiencyLevel,\n    description\n  }\n": TECHNOLOGIES_BY_CATEGORY_QUERYResult;
  }
}
